[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "muffin"
version = "0.1.1"
description = "Mutli-features fusion"
dependencies = [
    #
]

[tool.setuptools.packages.find]
where = ["src"]